---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: us-east-2
# traits of worker nodes
nodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    iam:
      # polices added to worker node role
      withAddonPolicies:
        # allows read/write to zones in Route53
        externalDNS: true
        # required for ALB-ingress
        albIngress: true
